# Generated by Django 5.2.1 on 2025-06-05 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='magazine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='magazines/'),
        ),
        migrations.AddField(
            model_name='magazine',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.magazinecategory'),
        ),
    ]
