# Generated by Django 5.2.1 on 2025-06-05 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_magazine_cover_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magazine',
            old_name='image',
            new_name='cover_image',
        ),
    ]
