# Generated by Django 5.2.1 on 2025-06-09 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_image_magazine_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoshoot',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.magazinecategory'),
        ),
        migrations.AddField(
            model_name='photoshoot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photoshoots/'),
        ),
        migrations.AddField(
            model_name='photoshoot',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='photoshoot',
            name='type',
            field=models.CharField(blank=True, choices=[('editorial', 'Editorial'), ('commercial', 'Commercial'), ('portrait', 'Portrait'), ('fashion', 'Fashion'), ('beauty', 'Beauty')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='magazine_covers/'),
        ),
    ]
