# Generated by Django 5.2.1 on 2025-06-09 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_photoshoot_category_photoshoot_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runway',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.magazinecategory'),
        ),
        migrations.AddField(
            model_name='runway',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='runways/'),
        ),
        migrations.AddField(
            model_name='runway',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='runway',
            name='type',
            field=models.CharField(blank=True, choices=[('haute_couture', 'Haute Couture'), ('ready_to_wear', 'Ready-to-Wear'), ('resort', 'Resort'), ('bridal', 'Bridal'), ('menswear', 'Menswear')], max_length=20, null=True),
        ),
    ]
