# Generated by Django 5.2.1 on 2025-06-10 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_campaign_image_campaign_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='magazineorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='magazineorder',
            name='magazine',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='MagazineOrder',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
